learning_log/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/' , include('users.urls')),
    path('' , include('learning_logs.urls')),
]

learning_logs/urls.py
from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    path('', views.index , name='index'),
    path('topics/' , views.topics , name='topics'),
    path('topics/<int:topic_id>'  , views.topic , name='topic'),
    path('new_topic/' , views.new_topic , name='new_topic'),
    path('new_entry/<int:topic_id>' , views.new_entry , name='new_entry'),
    path('edit_entry/<int:entry_id>' , views.edit_entry , name='edit_entry')
]

users/urls.py
from django.urls import path , include

app_name = 'users'
urlpatterns = [
    path ('' , include('django.contrib.auth.urls')),
]

learning_logs/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    """A topic the user is learning about"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.text

class Entry(models.Model):

    topic =models.ForeignKey(Topic , on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Entries"

    def __str__(self):
        return f"{self.text[:50]}……"

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic , Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text' : ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':'Entry:'}
        widgets = {'text':forms.Textarea(attrs={'cols':80})}

learning_logs/views.py
from django.shortcuts import render ,redirect
from .models import Topic ,Entry
from .forms import TopicForm , EntryForm


# Create your views here.
def index(request):
    return render(request , 'learning_logs/index.html')


def topics(request):
    topics = Topic.objects.order_by("date_added")
    context = {'topics' : topics}
    return render(request , 'learning_logs/topics.html' , context)


def topic(request , topic_id):
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by("-date_added")
    context = {'topic': topic , 'entries':entries}
    return render(request , 'learning_logs/topic.html' , context)


def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()

    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topics')
        
    context = {'form':form}
    return render(request , 'learning_logs/new_topic.html' ,context)


def new_entry(request , topic_id):
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST' :
        form = EntryForm()

    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic' , topic_id = topic_id)
        
    context = {'topic':topic , 'form':form}
    return render(request , 'learning_logs/new_entry.html' , context)


def edit_entry(request , entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if request.method != 'POST':
        form = EntryForm(instance=entry)

    else:
        form =EntryForm(instance=entry , data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic',topic_id=topic.id)
        
    context = {'entry':entry , 'topic':topic , 'form':form}
    return render(request , 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render

# Create your views here.

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>
        <a href="{% url 'learning_logs:index' %}">Learning_Logs</a> - 
        <a href="{% url 'learning_logs:topics' %}">Topics</a> -
        {% if user.is_authenticated %}
        Hello , {{user.username}}. -
        <a href="{% url 'users:logout' %}">Log out</a>
        {% else %}
        <a href="{% url 'users:login' %}">Log in</a>
        {% endif %}
    </p>

    {% block content %} {% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/index.html' %}

{% block content %}

<p><a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></p>
<p>Edit Entry</p>

<form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">

    {% csrf_token %}
    {{form.as_p}}
    <button name="submit">Save change</button>

</form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends "learning_logs/base.html" %}

    {% block content %}
    <p>html template test and inheretance process home learning_logs page</p>
    {% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/index.html' %}

{% block content %}
<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
<form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button name="submit">Add Entry</button>
</form>


{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p>Add New Topic:</p>
<form action='{% url "learning_logs:new_topic" %}' method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button name="submit">Add topic</button>
</form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>topic</title>
</head>
<body>
    {% extends 'learning_logs/base.html' %}

    {% block content %}

    <h3>Topic: {{topic}}</h3>
    <p><a href="{% url 'learning_logs:new_entry' topic.id %}">Add Entry</a></p>
    
    <ul>
        {% for entry in entries %}
        <li>{{entry.date_added|date:'M d , Y H:i'}}</li>
        <li>{{entry.text|linebreaks}}</li>
        <p><a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a></p>
        {% empty %}
        <p>there is not any entries yet .</p>
        {% endfor %}
    </ul>
    {% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/topics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Topics</title>
</head>
<body>
    {% extends "learning_logs/base.html" %}
    {% block content %}
    <p>Topics</p>
    <ul>
        {% for topic in topics %}
        <li>
            <a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a>
        </li>
        {% empty %}
        <p>there is no topics yet .</p>
        {% endfor %}
    </ul>
    <a href="{% url 'learning_logs:new_topic' %}">add new_topic</a>
    {% endblock content %}
</body>
</html>

users/templates/rejistrations/logged_out.html
{% extends 'learning_logs/base.html' %}

{% block content %}

<form action="{% url 'users:logout' %}" method="post">
  {% csrf_token %}
  <button type="submit">Logout</button>
</form>

{% endblock content %}

users/templates/rejistrations/login.html
{% extends 'learning_logs/base.html' %}

{% block content %}

{% if form.errors %}
<p>your user name and password didn`t match. please try again .</p>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button name="submit">Log in</button>
    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}">
</form>

{% endblock content %}